name: gridflow_env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.0=h88fedcc_1
  - azure-identity-cpp=1.12.0=hd83eed2_0
  - azure-storage-blobs-cpp=12.14.0=he094cc7_1
  - azure-storage-common-cpp=12.10.0=h12fd690_2
  - azure-storage-files-datalake-cpp=12.12.0=h30213e0_3
  - blosc=1.21.6=h7dd00d9_1
  - bokeh=3.4.2=pyhd8ed1ab_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.0.9=py39h23fbdae_8
  - brunsli=0.1=h97083b6_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - c-blosc2=2.15.2=h9cbb436_1
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h7f933ea_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.0=py39h85b62ae_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py39hf3bc14e_0
  - dask=2024.8.0=pyhd8ed1ab_0
  - dask-core=2024.8.0=pyhd8ed1ab_0
  - dask-expr=1.1.10=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.16=py39hd866990_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2024.8.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fiona=1.10.1=py39h77209e7_3
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.59.1=py39hb270ea8_0
  - freetype=2.14.1=hce30654_0
  - freexl=2.0.0=h3ab3353_2
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - gdal=3.10.2=py39hd0a36ac_5
  - geopandas=1.0.1=pyhd8ed1ab_3
  - geopandas-base=1.0.1=pyha770c72_3
  - geos=3.13.1=hc9a1286_0
  - geotiff=1.7.4=hbef4fa4_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.12.30=py39hf95bb6d_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.7=py39h157d57c_0
  - krb5=1.21.3=h237132a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libarchive=3.7.7=h3c2f2b0_4
  - libarrow=21.0.0=hd43feaf_8_cpu
  - libarrow-acero=21.0.0=hc317990_8_cpu
  - libarrow-compute=21.0.0=h75845d1_8_cpu
  - libarrow-dataset=21.0.0=hc317990_8_cpu
  - libarrow-substrait=21.0.0=h144af7f_8_cpu
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.5=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.23=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgdal-core=3.10.2=h0528216_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - libjxl=0.11.1=h7274d02_4
  - libkml=1.3.0=hc33e383_1022
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h45c8936_8_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - librttopo=1.1.0=h26cc057_18
  - libsodium=1.0.20=h99b78c6_0
  - libspatialindex=2.1.0=h57eeb1c_0
  - libspatialite=5.1.0=haf574c3_13
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.0=h551f018_4
  - libutf8proc=2.11.1=hd2415e0_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py39h131c74d_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39hefdd603_1
  - matplotlib=3.9.4=py39hdf13c20_0
  - matplotlib-base=3.9.4=py39h7251d6c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.10=hff1a8ea_0
  - msgpack-python=1.1.1=py39he2d979d_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h11e0b38_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=2.0.2=py39h3ba1154_1
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h6aaa60c_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39hfea3036_0
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - proj=9.5.1=h1318a7e_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39hf3bc14e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py39hdf13c20_0
  - pyarrow-core=21.0.0=py39h31423f9_0_cpu
  - pyarrow-hotfix=0.7=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.10.0=py39h77209e7_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyproj=3.6.1=py39hc1aa914_10
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=h7139b31_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.6.0=py39h161d348_0
  - pyyaml=6.0.2=py39hefdd603_2
  - pyzmq=27.0.2=py39h6c7bd39_0
  - qhull=2020.2=h420ef59_5
  - rasterio=1.4.3=py39ha3cb5d6_0
  - rasterstats=0.20.0=pyhd8ed1ab_1
  - rav1e=0.7.1=h0716509_3
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rioxarray=0.15.0=pyhd8ed1ab_0
  - rtree=1.4.1=pyh11ca60a_0
  - scikit-image=0.24.0=py39hbc50386_3
  - scikit-learn=1.6.1=py39h451895d_0
  - scipy=1.13.1=py39h3d5391c_0
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.0.7=py39ha3f5d07_1
  - simplejson=3.20.1=py39hf3bc14e_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hd121638_0
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.51.0=h81ab1b7_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=h12ba402_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py39he7485ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py39hf3bc14e_0
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x265=3.5=hbc6ce65_3
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=h92fc2f4_2
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zfp=1.0.1=hfd287c0_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.23.0=py39he7485ab_3
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/anaconda3/envs/gridflow_env
