name: gridflow-env
channels:
  # use conda-forge for better compatibility management of
  # geospatial packages.
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10

  # basic scientific packages
  - numpy
  - pandas
  - matplotlib
  - scipy

  # geospatial packages
  - geopandas>=1.0
  - shapely>=2.0
  - fiona>=1.10
  - pyproj>=3.6
  - rtree
  - rasterio
  - rioxarray
  - rasterstats
  - pyogrio

  # image processing
  - scikit-image

  # parallel / lazy evaluation
  - dask
  - distributed
  - xarray

  # standard utilities
  - requests
  - pyyaml
  - tqdm

  # plotting & visualization
  - mapclassify
  - xyzservices

  # jupyter (for demos)
  - notebook
  - jupyterlab

